#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Intertial Navigation System prototype data decoder

This script reads binary '.dat' files generated by the Jua Labs's INS and 
converts to readable JSON file format

{License_info}
"""

# Futures
# ...

# Built-in/Generic Imports
import struct
import json
import csv

# Libs

# Own modules
# ...

__author__ = 'Victor Medeiros'
__copyright__ = 'Copyright 2021, JuaLabs'
__credits__ = ['Victor Medeiros']
__license__ = '{license}'
__version__ = '0.1.1'
__maintainer__ = 'Victor Medeiros'
__email__ = 'victor.wanderley@ufrpe.br'
__status__ = 'developer'


input_filename = 'captura-05.dat'
output_filename = 'output-05.csv'
packet_format = '>BLhhhhhhhhhh'
converted_data = []

def main():
    with open(input_filename, "rb") as infile:
        byte = infile.read(1)
        while byte:
            if(byte == b'\x24'):
                packet = infile.read(25)
                end_packet = infile.read(2)
                # verifies if it is a valid packet
                if(end_packet == b'\x0D\x0A'):
                    converted_data.append(list(struct.unpack(packet_format, packet)))
            byte = infile.read(1)
            
        # adjust quaternion values
        # for l in converted_data:
        #     l[2] = l[2] / 16384.0
        #     l[3] = l[3] / 16384.0
        #     l[4] = l[4] / 16384.0
        #     l[5] = l[5] / 16384.0

        with open(output_filename, 'w') as outfile:
            csv_out=csv.writer(outfile)
            # csv_out.writerow(['mpu_id','ts','qw','qx','qy','qz','ax','ay','az','gx','gy','gz'])
            for row in converted_data:
                csv_out.writerow(row)

if __name__ == '__main__':
    main()
